from app.services.brand_team.dto import TeamDto, TeamWithMatesDto
from app.services.mate.interface import IMateService
from app.ports.userservice import IUserServicePort
from collections import defaultdict
from typing import Protocol


class ITeamService(Protocol):
    user_service: IUserServicePort
    mate_service: IMateService

    async def get_team_by_id(self, team_id: int) -> TeamDto: ...
    async def get_name_map(self) -> defaultdict[int, str | None]: ...
    async def exists(self, team_id: int) -> bool: ...
    async def create(self, name: str, owner_id: int) -> TeamDto: ...
    async def get_info(self, team_id: int) -> TeamWithMatesDto: ...
    async def update_name(self, team_id: int, new_name: str) -> TeamDto: ...
    async def delete(self, team_id: int) -> None: ...
    async def get_by_mate(self, user_id: int) -> TeamWithMatesDto: ...
    async def get_by_captain(self, captain_id: int) -> TeamDto: ...
    async def get_all(self) -> list[TeamDto]: ...
